### ISSUE TITLE
Configurable generators

### ISSUE THREAD

**Issue by duritong** [duritong/trocla#33]
As mentioned in #14 by @XANi we could define some templates within a config:

```
profiles:
    shellsafe:
        keygen: random
        options:
            allowed_chars: "a-zA-Z0-9"
            length: 16
    db_pass:
        keygen: random
        options:
            length: 32
    shadow_pass:
        keygen: random
        options:
            length: 16
            hash: sha1-salt
    base64_pass:
        keygen: random
        options:
            hash: sha256
            encoder: base64
    tmpfile:
        keygen: random
        options:
            length: 10
            allowed_chars: [ ":letters" ,  ":numbers" ]
            prefix: /tmp
    selfsigned:
        keygen: x509
        options:
            selfsigned: true
            subject: "/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=#{keyname}.#{fqdn}"
    internal-ca:
        keygen: x509
        options:
            root-ca: /some/where/root.ca
            root-ca-key: /some/where/root.key
            root-ca-passfile: /some/where/root.pass
```
